### PR TITLE
Seg fault42

### PR DESCRIPTION
**Pull request by SegFault42**
Don't forget to create nXDowload folder

Some cleanup see commit for details

### CODE REVIEW

**Comment by SegFault42** [comment]
Fix also race condition. What happen if crash after remove func ?

When you rename a file with a existing filename, you don't need to remove the file.

**Comment by 0d3n3h547v** [comment]
oh i see what you mean. Thanks for helping me out

**Comment by 0d3n3h547v** [comment]
Fixed. Waiting new pull request 👍

**Comment by SegFault42** [comment]
i'm working on it :)

**Pull request closed without merging**
